import * as Yup from "yup";

const isMainSection = (currentSectionName) =>
  !!(currentSectionName === "Career" || currentSectionName === "Education");

const getFormikData = (
  currentSectionName,
  entryBeingEdited,
  isCurrentlyEditing
) => {
  const initialValues = () => {
    return isMainSection(currentSectionName)
      ? {
          status: isCurrentlyEditing ? entryBeingEdited.status : false,
          establishment: isCurrentlyEditing
            ? entryBeingEdited.establishment
            : "",
          context: isCurrentlyEditing ? entryBeingEdited.context : "",
          startDate: isCurrentlyEditing ? entryBeingEdited.startDate : "",
          endDate: isCurrentlyEditing ? entryBeingEdited.endDate : "",
          description: isCurrentlyEditing ? entryBeingEdited.description : "",
        }
      : {
          extra: isCurrentlyEditing ? entryBeingEdited.status : false,
          proficiency: isCurrentlyEditing ? entryBeingEdited.proficiency : "",
        };
  };

  const validationSchema = () => {
    return isMainSection(currentSectionName)
      ? Yup.object({
          status: Yup.boolean(),
          establishment: Yup.string().required(
            `Please enter the name of the ${
              currentSectionName === "Career" ? "company" : "school"
            }`
          ),
          context: Yup.string().required(
            `Please enter your ${
              currentSectionName === "Career" ? "position" : "field"
            }`
          ),
          startDate: Yup.date().required("Please enter your starting date"),
          endDate: Yup.date(),
          description: Yup.string()
            .required("Please enter a description")
            .max(50),
        })
      : Yup.object({
          extra: Yup.string().required(
            `Please enter a ${
              (currentSectionName === "Hobbies" && "hobby") ||
              (currentSectionName === "Languages" && "language") ||
              (currentSectionName === "Tools" && "tools")
            }`
          ),
          proficiency: Yup.string().required("Please enter your skill level"),
        });
  };

  return {
    initialValues: initialValues(),
    validationSchema: validationSchema(),
  };
};

const getFieldsContents = (currentSectionName) => {
  const contents = () => {
    return isMainSection(currentSectionName)
      ? {
          status: {
            label: `I am still ${
              currentSectionName === "Career"
                ? "working for this company"
                : "studying at this school"
            }.`,
          },
          establishment: {
            label: `${currentSectionName === "Career" ? "Company" : "School"}`,
            placeholder: `${
              currentSectionName === "Career" ? "Microsoft" : "Harvard"
            }`,
          },
          context: {
            label: `${currentSectionName === "Career" ? "Position" : "Field"}`,
            placeholder: `${
              currentSectionName === "Career" ? "CEO" : "Economics"
            }`,
          },
          description: {
            label: `About your ${
              currentSectionName === "Career" ? "work" : "studies"
            }`,
            placeholder: `${
              currentSectionName === "Career"
                ? "Your tasks & developed projects"
                : "Your focus points & main takeaways"
            }`,
          },
        }
      : {
          label: `${
            (currentSectionName === "Tools" && "Tool") ||
            (currentSectionName === "Languages" && "Language") ||
            (currentSectionName === "Hobbies" && "Hobby")
          }`,
          placeholder: `${
            (currentSectionName === "Tools" && "Microsoft Office") ||
            (currentSectionName === "Languages" && "French") ||
            (currentSectionName === "Hobbies" && "Woodworking")
          }`,
        };
  };

  const dropdown = {
    Tools: [
      "Adobe Photoshop",
      "Adobe Illustrator",
      "Adobe InDesign",
      "Microsoft Office",
      "Google Suite",
    ],
    Hobbies: [
      "3D printing",
      "Amateur radio",
      "Scrapbook",
      "Amateur radio",
      "Acting",
      "Baton twirling",
      "Board games",
      "Book restoration",
      "Cabaret",
      "Calligraphy",
      "Candle making",
      "Computer programming",
      "Coffee roasting",
      "Cooking",
      "Colouring",
      "Cosplaying",
      "Couponing",
      "Creative writing",
      "Crocheting",
      "Cryptography",
      "Dance",
      "Digital arts",
      "Drama",
      "Drawing",
      "Do it yourself",
      "Electronics",
      "Embroidery",
      "Fashion",
      "Flower arranging",
      "Foreign language learning",
      "Gaming",
      "Tabletop games",
      "Role-playing games",
      "Gambling",
      "Genealogy",
      "Glassblowing",
      "Gunsmithing",
      "Homebrewing",
      "Ice skating",
      "Jewelry making",
      "Jigsaw puzzles",
      "Juggling",
      "Knapping",
      "Knitting",
      "Kabaddi",
      "Knife making",
      "Lacemaking",
      "Lapidary",
      "Leather crafting",
      "Lego building",
      "Lockpicking",
      "Machining",
      "Macrame",
      "Metalworking",
      "Magic",
      "Model building",
      "Listening to music",
      "Origami",
      "Painting",
      "Playing musical instruments",
      "Pet",
      "Poi",
      "Pottery",
      "Puzzles",
      "Quilting",
      "Reading",
      "Scrapbooking",
      "Sculpting",
      "Sewing",
      "Singing",
      "Sketching",
      "Soapmaking",
      "Sports",
      "Stand-up comedy",
      "Sudoku",
      "Table tennis",
      "Taxidermy",
      "Video gaming",
      "Watching movies",
      "Web surfing",
      "Whittling",
      "Wood carving",
      "Woodworking",
      "World Building",
      "Writing",
      "Yoga",
      "Yo-yoing",
      "Air sports",
      "Archery",
      "Astronomy",
      "Backpacking",
      "Base jumping",
      "Baseball",
      "Basketball",
      "Beekeeping",
      "Bird watching",
      "Blacksmithing",
      "Board sports",
      "Bodybuilding",
      "Brazilian jiu-jitsu",
      "Community",
      "Cycling",
      "Dowsing",
      "Driving",
      "Fishing",
      "Flag football",
      "Flying",
      "Flying disc",
      "Foraging",
      "Gardening",
      "Geocaching",
      "Ghost hunting",
      "Graffiti",
      "Handball",
      "Hiking",
      "Hooping",
      "Horseback riding",
      "Hunting",
      "Inline skating",
      "Jogging",
      "Kayaking",
      "Kite flying",
      "Kitesurfing",
      "Larping",
      "Letterboxing",
      "Metal detecting",
      "Motor sports",
      "Mountain biking",
      "Mountaineering",
      "Mushroom hunting",
      "Mycology",
      "Netball",
      "Nordic skating",
      "Orienteering",
      "Paintball",
      "Parkour",
      "Photography",
      "Polo",
      "Rafting",
      "Rappelling",
      "Rock climbing",
      "Roller skating",
      "Rugby",
      "Running",
      "Sailing",
      "Sand art",
      "Scouting",
      "Scuba diving",
      "Sculling",
      "Rowing",
      "Shooting",
      "Shopping",
      "Skateboarding",
      "Skiing",
      "Skim Boarding",
      "Skydiving",
      "Slacklining",
      "Snowboarding",
      "Stone skipping",
      "Surfing",
      "Swimming",
      "Taekwondo",
      "Tai chi",
      "Urban exploration",
      "Vacation",
      "Vehicle restoration",
      "Water sports",
    ],
    Languages: [
      [
        "Abkhazian",
        "Afar",
        "Afrikaans",
        "Akan",
        "Albanian",
        "Amharic",
        "Arabic",
        "Aragonese",
        "Armenian",
        "Assamese",
        "Avaric",
        "Avestan",
        "Aymara",
        "Azerbaijani",
        "Bambara",
        "Bashkir",
        "Basque",
        "Belarusian",
        "Bengali",
        "Bihari languages",
        "Bislama",
        "Bosnian",
        "Breton",
        "Bulgarian",
        "Burmese",
        "Catalan, Valencian",
        "Central Khmer",
        "Chamorro",
        "Chechen",
        "Chichewa, Chewa, Nyanja",
        "Chinese",
        "Church Slavonic, Old Bulgarian, Old Church Slavonic",
        "Chuvash",
        "Cornish",
        "Corsican",
        "Cree",
        "Croatian",
        "Czech",
        "Danish",
        "Divehi, Dhivehi, Maldivian",
        "Dutch, Flemish",
        "Dzongkha",
        "English",
        "Esperanto",
        "Estonian",
        "Ewe",
        "Faroese",
        "Fijian",
        "Finnish",
        "French",
        "Fulah",
        "Gaelic, Scottish Gaelic",
        "Galician",
        "Ganda",
        "Georgian",
        "German",
        "Gikuyu, Kikuyu",
        "Greek (Modern)",
        "Greenlandic, Kalaallisut",
        "Guarani",
        "Gujarati",
        "Haitian, Haitian Creole",
        "Hausa",
        "Hebrew",
        "Herero",
        "Hindi",
        "Hiri Motu",
        "Hungarian",
        "Icelandic",
        "Ido",
        "Igbo",
        "Indonesian",
        "Interlingua (International Auxiliary Language Association)",
        "Interlingue",
        "Inuktitut",
        "Inupiaq",
        "Irish",
        "Italian",
        "Japanese",
        "Javanese",
        "Kannada",
        "Kanuri",
        "Kashmiri",
        "Kazakh",
        "Kinyarwanda",
        "Komi",
        "Kongo",
        "Korean",
        "Kwanyama, Kuanyama",
        "Kurdish",
        "Kyrgyz",
        "Lao",
        "Latin",
        "Latvian",
        "Letzeburgesch, Luxembourgish",
        "Limburgish, Limburgan, Limburger",
        "Lingala",
        "Lithuanian",
        "Luba-Katanga",
        "Macedonian",
        "Malagasy",
        "Malay",
        "Malayalam",
        "Maltese",
        "Manx",
        "Maori",
        "Marathi",
        "Marshallese",
        "Moldovan, Moldavian, Romanian",
        "Mongolian",
        "Nauru",
        "Navajo, Navaho",
        "Northern Ndebele",
        "Ndonga",
        "Nepali",
        "Northern Sami",
        "Norwegian",
        "Norwegian Bokmål",
        "Norwegian Nynorsk",
        "Nuosu, Sichuan Yi",
        "Occitan (post 1500)",
        "Ojibwa",
        "Oriya",
        "Oromo",
        "Ossetian, Ossetic",
        "Pali",
        "Panjabi, Punjabi",
        "Pashto, Pushto",
        "Persian",
        "Polish",
        "Portuguese",
        "Quechua",
        "Romansh",
        "Rundi",
        "Russian",
        "Samoan",
        "Sango",
        "Sanskrit",
        "Sardinian",
        "Serbian",
        "Shona",
        "Sindhi",
        "Sinhala, Sinhalese",
        "Slovak",
        "Slovenian",
        "Somali",
        "Sotho, Southern",
        "South Ndebele",
        "Spanish, Castilian",
        "Sundanese",
        "Swahili",
        "Swati",
        "Swedish",
        "Tagalog",
        "Tahitian",
        "Tajik",
        "Tamil",
        "Tatar",
        "Telugu",
        "Thai",
        "Tibetan",
        "Tigrinya",
        "Tonga (Tonga Islands)",
        "Tsonga",
        "Tswana",
        "Turkish",
        "Turkmen",
        "Twi",
        "Uighur, Uyghur",
        "Ukrainian",
        "Urdu",
        "Uzbek",
        "Venda",
        "Vietnamese",
        "Volap_k",
        "Walloon",
        "Welsh",
        "Western Frisian",
        "Wolof",
        "Xhosa",
        "Yiddish",
        "Yoruba",
        "Zhuang, Chuang",
        "Zulu",
      ],
    ],
  };
  return { contents: contents(), dropdown: dropdown[currentSectionName] };
};

export { getFieldsContents, getFormikData, isMainSection };
